In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv(r"C:\Users\amitthakur3\Downloads\Machine-Learning-with-Python-and-Scikit-master\Machine-Learning-with-Python-and-Scikit-master\Datasets\Mall_Customers.csv")

In [13]:
## Creation of Dependent and Independent Variable
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [14]:
print(x)

[[1 'Male' 19 15]
 [2 'Male' 21 15]
 [3 'Female' 20 16]
 [4 'Female' 23 16]
 [5 'Female' 31 17]
 [6 'Female' 22 17]
 [7 'Female' 35 18]
 [8 'Female' 23 18]
 [9 'Male' 64 19]
 [10 'Female' 30 19]
 [11 'Male' 67 19]
 [12 'Female' 35 19]
 [13 'Female' 58 20]
 [14 'Female' 24 20]
 [15 'Male' 37 20]
 [16 'Male' 22 20]
 [17 'Female' 35 21]
 [18 'Male' 20 21]
 [19 'Male' 52 23]
 [20 'Female' 35 23]
 [21 'Male' 35 24]
 [22 'Male' 25 24]
 [23 'Female' 46 25]
 [24 'Male' 31 25]
 [25 'Female' 54 28]
 [26 'Male' 29 28]
 [27 'Female' 45 28]
 [28 'Male' 35 28]
 [29 'Female' 40 29]
 [30 'Female' 23 29]
 [31 'Male' 60 30]
 [32 'Female' 21 30]
 [33 'Male' 53 33]
 [34 'Male' 18 33]
 [35 'Female' 49 33]
 [36 'Female' 21 33]
 [37 'Female' 42 34]
 [38 'Female' 30 34]
 [39 'Female' 36 37]
 [40 'Female' 20 37]
 [41 'Female' 65 38]
 [42 'Male' 24 38]
 [43 'Male' 48 39]
 [44 'Female' 31 39]
 [45 'Female' 49 39]
 [46 'Female' 24 39]
 [47 'Female' 50 40]
 [48 'Female' 27 40]
 [49 'Female' 29 40]
 [50 'Female' 31

In [25]:
x[:,1:2]

array([['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Femal

In [15]:
print(y)

[39 81  6 77 40 76  6 94  3 72 14 99 15 77 13 79 35 66 29 98 35 73  5 73
 14 82 32 61 31 87  4 73  4 92 14 81 17 73 26 75 35 92 36 61 28 65 55 47
 42 42 52 60 54 60 45 41 50 46 51 46 56 55 52 59 51 59 50 48 59 47 55 42
 49 56 47 54 53 48 52 42 51 55 41 44 57 46 58 55 60 46 55 41 49 40 42 52
 47 50 42 49 41 48 59 55 56 42 50 46 43 48 52 54 42 46 48 50 43 59 43 57
 56 40 58 91 29 77 35 95 11 75  9 75 34 71  5 88  7 73 10 72  5 93 40 87
 12 97 36 74 22 90 17 88 20 76 16 89  1 78  1 73 35 83  5 93 26 75 20 95
 27 63 13 75 10 92 13 86 15 69 14 90 32 86 15 88 39 97 24 68 17 85 23 69
  8 91 16 79 28 74 18 83]


### Missing Data Treatment

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:,2:4])
x[:,2:4] = imputer.transform(x[:,2:4])

In [23]:
print(x)

[[1 'Male' 19.0 15.0]
 [2 'Male' 21.0 15.0]
 [3 'Female' 20.0 16.0]
 [4 'Female' 23.0 16.0]
 [5 'Female' 31.0 17.0]
 [6 'Female' 22.0 17.0]
 [7 'Female' 35.0 18.0]
 [8 'Female' 23.0 18.0]
 [9 'Male' 64.0 19.0]
 [10 'Female' 30.0 19.0]
 [11 'Male' 67.0 19.0]
 [12 'Female' 35.0 19.0]
 [13 'Female' 58.0 20.0]
 [14 'Female' 24.0 20.0]
 [15 'Male' 37.0 20.0]
 [16 'Male' 22.0 20.0]
 [17 'Female' 35.0 21.0]
 [18 'Male' 20.0 21.0]
 [19 'Male' 52.0 23.0]
 [20 'Female' 35.0 23.0]
 [21 'Male' 35.0 24.0]
 [22 'Male' 25.0 24.0]
 [23 'Female' 46.0 25.0]
 [24 'Male' 31.0 25.0]
 [25 'Female' 54.0 28.0]
 [26 'Male' 29.0 28.0]
 [27 'Female' 45.0 28.0]
 [28 'Male' 35.0 28.0]
 [29 'Female' 40.0 29.0]
 [30 'Female' 23.0 29.0]
 [31 'Male' 60.0 30.0]
 [32 'Female' 21.0 30.0]
 [33 'Male' 53.0 33.0]
 [34 'Male' 18.0 33.0]
 [35 'Female' 49.0 33.0]
 [36 'Female' 21.0 33.0]
 [37 'Female' 42.0 34.0]
 [38 'Female' 30.0 34.0]
 [39 'Female' 36.0 37.0]
 [40 'Female' 20.0 37.0]
 [41 'Female' 65.0 38.0]
 [42 'Male' 24.0

### Categorical data --> one hot encoding

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [1])] ,remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 1 19.0 15.0]
 [0.0 1.0 2 21.0 15.0]
 [1.0 0.0 3 20.0 16.0]
 [1.0 0.0 4 23.0 16.0]
 [1.0 0.0 5 31.0 17.0]
 [1.0 0.0 6 22.0 17.0]
 [1.0 0.0 7 35.0 18.0]
 [1.0 0.0 8 23.0 18.0]
 [0.0 1.0 9 64.0 19.0]
 [1.0 0.0 10 30.0 19.0]
 [0.0 1.0 11 67.0 19.0]
 [1.0 0.0 12 35.0 19.0]
 [1.0 0.0 13 58.0 20.0]
 [1.0 0.0 14 24.0 20.0]
 [0.0 1.0 15 37.0 20.0]
 [0.0 1.0 16 22.0 20.0]
 [1.0 0.0 17 35.0 21.0]
 [0.0 1.0 18 20.0 21.0]
 [0.0 1.0 19 52.0 23.0]
 [1.0 0.0 20 35.0 23.0]
 [0.0 1.0 21 35.0 24.0]
 [0.0 1.0 22 25.0 24.0]
 [1.0 0.0 23 46.0 25.0]
 [0.0 1.0 24 31.0 25.0]
 [1.0 0.0 25 54.0 28.0]
 [0.0 1.0 26 29.0 28.0]
 [1.0 0.0 27 45.0 28.0]
 [0.0 1.0 28 35.0 28.0]
 [1.0 0.0 29 40.0 29.0]
 [1.0 0.0 30 23.0 29.0]
 [0.0 1.0 31 60.0 30.0]
 [1.0 0.0 32 21.0 30.0]
 [0.0 1.0 33 53.0 33.0]
 [0.0 1.0 34 18.0 33.0]
 [1.0 0.0 35 49.0 33.0]
 [1.0 0.0 36 21.0 33.0]
 [1.0 0.0 37 42.0 34.0]
 [1.0 0.0 38 30.0 34.0]
 [1.0 0.0 39 36.0 37.0]
 [1.0 0.0 40 20.0 37.0]
 [1.0 0.0 41 65.0 38.0]
 [0.0 1.0 42 24.0 38.0]
 

## Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size = 0.2, random_state=1)

In [33]:
print(x_train)

[[0.0 1.0 109 68.0 63.0]
 [0.0 1.0 108 54.0 63.0]
 [1.0 0.0 190 36.0 103.0]
 [0.0 1.0 15 37.0 20.0]
 [1.0 0.0 57 51.0 44.0]
 [1.0 0.0 20 35.0 23.0]
 [1.0 0.0 115 18.0 65.0]
 [1.0 0.0 40 20.0 37.0]
 [0.0 1.0 186 30.0 99.0]
 [1.0 0.0 125 23.0 70.0]
 [0.0 1.0 99 48.0 61.0]
 [0.0 1.0 124 39.0 69.0]
 [1.0 0.0 120 50.0 67.0]
 [0.0 1.0 54 59.0 43.0]
 [0.0 1.0 34 18.0 33.0]
 [0.0 1.0 180 35.0 93.0]
 [1.0 0.0 182 32.0 97.0]
 [1.0 0.0 107 66.0 63.0]
 [0.0 1.0 200 30.0 137.0]
 [0.0 1.0 139 19.0 74.0]
 [1.0 0.0 117 63.0 65.0]
 [1.0 0.0 68 68.0 48.0]
 [1.0 0.0 79 23.0 54.0]
 [0.0 1.0 43 48.0 39.0]
 [0.0 1.0 18 20.0 21.0]
 [1.0 0.0 6 22.0 17.0]
 [0.0 1.0 128 40.0 71.0]
 [1.0 0.0 106 21.0 62.0]
 [1.0 0.0 49 29.0 40.0]
 [1.0 0.0 67 43.0 48.0]
 [1.0 0.0 55 50.0 43.0]
 [1.0 0.0 85 21.0 54.0]
 [1.0 0.0 184 29.0 98.0]
 [0.0 1.0 159 34.0 78.0]
 [0.0 1.0 167 42.0 86.0]
 [0.0 1.0 114 19.0 64.0]
 [1.0 0.0 13 58.0 20.0]
 [1.0 0.0 118 49.0 65.0]
 [1.0 0.0 94 40.0 60.0]
 [0.0 1.0 121 27.0 67.0]
 [1.0 0.0 155 47.

In [34]:
print(x_test)

[[1.0 0.0 59 27.0 46.0]
 [1.0 0.0 41 65.0 38.0]
 [1.0 0.0 35 49.0 33.0]
 [0.0 1.0 103 67.0 62.0]
 [1.0 0.0 185 41.0 99.0]
 [0.0 1.0 199 32.0 137.0]
 [0.0 1.0 96 24.0 60.0]
 [1.0 0.0 5 31.0 17.0]
 [1.0 0.0 30 23.0 29.0]
 [1.0 0.0 169 36.0 87.0]
 [0.0 1.0 172 28.0 87.0]
 [0.0 1.0 19 52.0 23.0]
 [1.0 0.0 12 35.0 19.0]
 [1.0 0.0 90 50.0 58.0]
 [0.0 1.0 111 65.0 63.0]
 [1.0 0.0 119 51.0 67.0]
 [1.0 0.0 160 30.0 78.0]
 [1.0 0.0 36 21.0 33.0]
 [1.0 0.0 137 44.0 73.0]
 [0.0 1.0 60 53.0 46.0]
 [0.0 1.0 52 33.0 42.0]
 [1.0 0.0 17 35.0 21.0]
 [1.0 0.0 45 49.0 39.0]
 [1.0 0.0 95 32.0 60.0]
 [1.0 0.0 32 21.0 30.0]
 [0.0 1.0 163 19.0 81.0]
 [1.0 0.0 39 36.0 37.0]
 [1.0 0.0 29 40.0 29.0]
 [1.0 0.0 194 38.0 113.0]
 [0.0 1.0 28 35.0 28.0]
 [1.0 0.0 48 27.0 40.0]
 [1.0 0.0 166 36.0 85.0]
 [1.0 0.0 195 47.0 120.0]
 [0.0 1.0 178 27.0 88.0]
 [0.0 1.0 177 58.0 88.0]
 [1.0 0.0 98 27.0 60.0]
 [1.0 0.0 175 52.0 88.0]
 [1.0 0.0 74 60.0 50.0]
 [1.0 0.0 70 32.0 48.0]
 [0.0 1.0 173 36.0 87.0]]


## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] =  sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] =  sc.transform(x_test[:, 3:])

In [36]:
print(x_train)


[[0.0 1.0 109 2.0605301243169722 0.08807565819256034]
 [0.0 1.0 108 1.0730274545544523 0.08807565819256034]
 [1.0 0.0 190 -0.1966188351402161 1.667023031952744]
 [0.0 1.0 15 -0.12608293015717897 -1.609292768599637]
 [1.0 0.0 57 0.8614197396053409 -0.6619243443435269]
 [1.0 0.0 20 -0.26715474012325324 -1.4908717155676232]
 [1.0 0.0 115 -1.4662651248348846 0.16702302688056953]
 [1.0 0.0 40 -1.3251933148688102 -0.938240134751559]
 [0.0 1.0 186 -0.619834265038439 1.5091282945767255]
 [1.0 0.0 125 -1.1135855999196989 0.36439144860059247]
 [0.0 1.0 99 0.6498120246562296 0.009128289504551173]
 [0.0 1.0 124 0.014988879808895291 0.32491776425658786]
 [1.0 0.0 120 0.7908838346223038 0.2459703955685787]
 [0.0 1.0 54 1.425706979469638 -0.7013980286875314]
 [0.0 1.0 34 -1.4662651248348846 -1.0961348721275772]
 [0.0 1.0 180 -0.26715474012325324 1.272286188512698]
 [1.0 0.0 182 -0.47876245507236465 1.4301809258887164]
 [1.0 0.0 107 1.9194583143508979 0.08807565819256034]
 [0.0 1.0 200 -0.619834265038

In [37]:
print(x_test)

[[1.0 0.0 59 -0.8314419799875503 -0.5829769756555176]
 [1.0 0.0 41 1.848922409367861 -0.8987664504075543]
 [1.0 0.0 35 0.7203479296392666 -1.0961348721275772]
 [0.0 1.0 103 1.989994219333935 0.04860197384855576]
 [1.0 0.0 185 0.15606068977496956 1.5091282945767255]
 [0.0 1.0 199 -0.47876245507236465 3.0091282996489]
 [0.0 1.0 96 -1.0430496949366617 -0.030345394839453414]
 [1.0 0.0 5 -0.5492983600554018 -1.7277138216316508]
 [1.0 0.0 30 -1.1135855999196989 -1.2540296095035957]
 [1.0 0.0 169 -0.1966188351402161 1.0354440824486704]
 [0.0 1.0 172 -0.7609060750045132 1.0354440824486704]
 [0.0 1.0 19 0.9319556445883781 -1.4908717155676232]
 [1.0 0.0 12 -0.26715474012325324 -1.6487664529436414]
 [1.0 0.0 90 0.7908838346223038 -0.10929276352746259]
 [0.0 1.0 111 1.848922409367861 0.08807565819256034]
 [1.0 0.0 119 0.8614197396053409 0.2459703955685787]
 [1.0 0.0 160 -0.619834265038439 0.6801809233526291]
 [1.0 0.0 36 -1.2546574098857732 -1.0961348721275772]
 [1.0 0.0 137 0.36766840472408097 0.